In [2]:
import numpy as np

#1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [3]:
vec = np.zeros(100)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#2.Создать вектор размера 100, заполненный единицами

In [4]:
vec = np.ones(100)
print(vec)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#3.Создать вектор размера 100, заполненный числом 3

In [21]:
vec = np.full(100, 3)
print(vec)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#4. Как получить документацию о функции numpy.add из командной строки?

In [7]:
np.add??

#5. Поменять 2 строки в матрице

In [22]:
vec = np.arange(25).reshape(5,-1)
vec[[0,4]] = vec[[4,0]]
print(vec)

[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


#6. Создать вектор со значениями от 10 до 100

In [23]:
vec = np.arange(10,101)
print(vec)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#7. Развернуть вектор (первый становится последним)

In [25]:
vec = np.arange(100)
vec = vec[::-1]
print(vec)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


#8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [26]:
vec = np.arange(16).reshape(4,4)
print(vec)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [27]:
vec = np.array([1, 2, 3, 4, 5])
num = 3
n = np.zeros(len(vec)+(len(v)-1)*num)
n[::num+1]=vec
print(n)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#10. Создать 3x3 единичную матрицу

In [28]:
vec = np.eye(3)
print(vec)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#11. Создать массив 3x3x3 со случайными значениями

In [29]:
vec = np.random.random((3,3,3))
print(vec)

[[[0.73919149 0.37623124 0.12012587]
  [0.24104976 0.14231287 0.99107121]
  [0.80213655 0.4931334  0.9838341 ]]

 [[0.52914389 0.07887849 0.40716167]
  [0.44392929 0.39388382 0.17263504]
  [0.08985377 0.77442334 0.32131559]]

 [[0.4235942  0.090227   0.57135571]
  [0.4941945  0.87053326 0.05504299]
  [0.66984887 0.72888797 0.57396773]]]


#12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [33]:
vec = np.random.random((10,10))
print(vec)
min, max = vec.min(), vec.max()
print(min, max)

[[0.45247361 0.44999705 0.23631878 0.83008906 0.14548387 0.11006617
  0.65394049 0.89667145 0.18152976 0.62061934]
 [0.07887176 0.02641818 0.96062372 0.81795153 0.1362659  0.11989376
  0.54995563 0.24443319 0.5775368  0.54221602]
 [0.57345224 0.82168056 0.08849799 0.13487263 0.19707027 0.40016307
  0.61767291 0.38534294 0.52167051 0.00705535]
 [0.28575722 0.10215227 0.15826899 0.33673532 0.23418355 0.01301921
  0.20608894 0.97545217 0.79998418 0.24222301]
 [0.51431496 0.88333899 0.3702601  0.89408179 0.94831578 0.19103551
  0.79552884 0.95470878 0.2450859  0.51015003]
 [0.64459252 0.23363562 0.341236   0.45643206 0.08445654 0.80817206
  0.48233436 0.28546694 0.77148585 0.59224846]
 [0.26164    0.19521792 0.81933481 0.96075853 0.07338868 0.94882685
  0.81071376 0.11973188 0.35798621 0.0930468 ]
 [0.55526627 0.31839068 0.08725533 0.18705905 0.90380824 0.67475374
  0.8575073  0.58132585 0.3978043  0.65052612]
 [0.37670889 0.22254515 0.96627888 0.91342194 0.00726614 0.51328549
  0.44588624

#13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [29]:
v = np.random.random(30)
m = v.mean()
print(v)
print(m)

[0.45743555 0.97835726 0.05861364 0.33998599 0.03446725 0.97004016
 0.27248384 0.99325561 0.2934836  0.81068396 0.23336379 0.34189343
 0.48554675 0.68213439 0.99737109 0.36150711 0.29499768 0.27526704
 0.96922948 0.22961229 0.04243148 0.41823486 0.6539342  0.55993107
 0.57395518 0.92237252 0.57168966 0.78721663 0.1446207  0.551926  ]
0.5102014059814972


#14. Создать матрицу с 0 внутри, и 1 на границах

In [32]:
vec = np.ones((10,10))
vec[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [35]:
vec = np.diag(np.arange(5))
vec

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [34]:
vec = np.diag(np.arange(1,5), k = -1)
print(vec)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [38]:
vec = np.zeros((8,8))
vec[::2, 1::2] = 1
vec[1::2, ::2] = 1
print(vec)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [39]:
vec = np.unravel_index(100, (6,7,8))
print(vec)

(1, 5, 4)


#19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [44]:
vec = np.tile(np.array([[0, 1],[1, 0]]), (4,4))
print(vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#20. Перемножить матрицы 5x3 и 3x2

In [39]:
a = np.ones((5,3))
b = np.ones((3,2))
vec = np.dot(a, b)
print(vec)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [41]:
vec = np.arange(10)
vec[(3<vec)&(vec<=8)] *= -1
print(vec)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [51]:
vec = np.zeros((5,5))
vec += np.arange(5)
print(vec)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#24. Есть генератор, сделать с его помощью массив

In [6]:
def generate():
    for x in range(10):
        yield x
v = np.fromiter(generate(),dtype=float,count=-1)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [44]:
v = np.linspace(0,1,12)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#26. Отсортировать вектор

In [8]:
v =np.random.random(10)
v.sort()
print(v)

[0.03501296 0.32091107 0.33264721 0.34489979 0.37786699 0.68228567
 0.71991127 0.84376247 0.87474724 0.87827622]


#27. Проверить, одинаковы ли 2 numpy массива

In [12]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equals = np.allclose(a, b)
print(a)
print(b)
print(equals)

[1 0 1 0 0]
[0 1 0 1 1]
False


#28. Сделать массив неизменяемым

In [18]:
v = np.ones(10)
print(v)
v.flags.writeable = False
v[F0] = 5 
print(v)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#29. Найти n наибольших значений в массиве

In [27]:
v = np.arange(100)
np.random.shuffle(v)
n = 5
print(v[np.argpartition(-v,n)[:n]])

[99 98 97 96 95]


#30. Заменить максимальный элемент на ноль

In [26]:
v = np.arange(10)
np.random.shuffle(v)
print(v)
max_arg = v.argmax()
v[max_arg] = 0
print(v)

[3 4 2 8 1 9 7 5 0 6]
[3 4 2 8 1 0 7 5 0 6]


#31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [6]:
v = np.zeros((5,5), [('x',float),('y',float)])
v['x'], v['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(v)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [13]:
x = np.arange(8)
y= x+1
c = 1/np.subtract.outer(x, y)
# print(np.subtract.outer(x, y))
print(c)

[[-1.         -0.5        -0.33333333 -0.25       -0.2        -0.16666667
  -0.14285714 -0.125     ]
 [        inf -1.         -0.5        -0.33333333 -0.25       -0.2
  -0.16666667 -0.14285714]
 [ 1.                 inf -1.         -0.5        -0.33333333 -0.25
  -0.2        -0.16666667]
 [ 0.5         1.                 inf -1.         -0.5        -0.33333333
  -0.25       -0.2       ]
 [ 0.33333333  0.5         1.                 inf -1.         -0.5
  -0.33333333 -0.25      ]
 [ 0.25        0.33333333  0.5         1.                 inf -1.
  -0.5        -0.33333333]
 [ 0.2         0.25        0.33333333  0.5         1.                 inf
  -1.         -0.5       ]
 [ 0.16666667  0.2         0.25        0.33333333  0.5         1.
          inf -1.        ]]


D:\Study\All\2 course\Intelligent data analysis in business\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [18]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max) 
    print(np.finfo(dtype).eps)
#     ?????

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#34. Напечатать все значения в массиве

35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
v = np.arange(100)
num = np.random.uniform(0,100)
print(v, num)
index = (np.abs(v-num)).argmin()
print(v[index])

#36. Преобразовать массив из float в int

In [27]:
v = np.arange(10, dtype = np.int32)
print(v)
v = v.astype(np.float32)
print(v)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#37. Каков эквивалент функции enumerate для numpy массивов?

In [34]:
v = np.arange(16).reshape(4,4)
print(v)
for index, value in np.ndenumerate(v):
    print(index, value)
for index, value in np.ndindex(v.shape):
    print(index, v[index])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
0 [0 1 2 3]
0 [0 1 2 3]
0 [0 1 2 3]
0 [0 1 2 3]
1 [4 5 6 7]
1 [4 5 6 7]
1 [4 5 6 7]
1 [4 5 6 7]
2 [ 8  9 10 11]
2 [ 8  9 10 11]
2 [ 8  9 10 11]
2 [ 8  9 10 11]
3 [12 13 14 15]
3 [12 13 14 15]
3 [12 13 14 15]
3 [12 13 14 15]


#38. Случайно расположить p элементов в 2D массив

In [42]:
n = 10
p = 15
v = np.zeros((n,n))
np.put(v, np.random.choice(range(n*n), p, replace=False), 1)
print(v)

[[0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#39. Отнять среднее из каждой строки в матрице

In [50]:
v = np.random.rand(5, 5)
print(v)
m = v.mean(axis=1, keepdims = True)
print(v-m)

[[0.33900056 0.22887481 0.20236967 0.51584908 0.99593373]
 [0.87543896 0.37244454 0.07802043 0.10428151 0.59294088]
 [0.9187942  0.33550412 0.17406621 0.93264265 0.34307657]
 [0.09672554 0.9134071  0.06706928 0.71314107 0.90527428]
 [0.1734373  0.03650345 0.36560591 0.63059383 0.83807625]]
[[-0.11740501 -0.22753076 -0.2540359   0.05944351  0.53952816]
 [ 0.4708137  -0.03218072 -0.32660483 -0.30034376  0.18831562]
 [ 0.37797746 -0.20531263 -0.36675054  0.3918259  -0.19774018]
 [-0.44239791  0.37428365 -0.47205417  0.17401762  0.36615082]
 [-0.23540605 -0.3723399  -0.04323744  0.22175049  0.4292329 ]]


#40. Отсортировать матрицу по n-ому столбцу

In [57]:
v = np.random.randint(0,10,(4,4))
print(v)
n=1
print(v[v[:,n].argsort()])

[[1 7 2 9]
 [6 1 8 7]
 [8 0 5 0]
 [0 0 2 1]]
[[8 0 5 0]
 [0 0 2 1]
 [6 1 8 7]
 [1 7 2 9]]


#41. Определить, есть ли в 2D массиве нулевые столбцы

In [81]:
v = np.random.randint(0, 5, (3,3))
print(v)
print((~v.any(axis=0)).any())

[[3 0 3]
 [3 1 4]
 [3 2 3]]
False


#42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [87]:
v = np.zeros(10)
mas =  np.random.randint(0, len(v), 20)
print(mas)
v += np.bincount(mas, minlength = len(v))
print(v)

[9 0 9 2 2 6 3 6 3 0 3 6 4 6 6 4 6 5 1 4]
[2. 1. 2. 3. 3. 1. 6. 0. 0. 2.]


#43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [93]:
w,h = 16, 16
mas = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
f = mas[...,0]*256*256 + mas[...,1]*256 + mas[...,2]
n= len(np.unique(f))
print(np.unique(mas))

[0 1]


#44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [99]:
mas = np.random.randint(0,10, (3,4,3,4))
s = mas.reshape(mas.shape[:-2] + (-1,)).sum(axis=-1)
print(s)

[[37 56 42 54]
 [55 50 78 49]
 [50 51 44 59]]
